---
title: "Draft Quarto document"
author: "Your Name"
format: html
execute:
  echo: true
editor:
    markdown:
        wrap: 72
        canonical: TRUE
---

```{r setup}
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Results

```{r basic-stats}
tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>%
  select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive statistics of the metabolites.")
```

```{r histogram-metabolites}
tar_read(fig_metabolite_distribution_plot)
```

## Building the model

### Running multiple model
```{r}
model_estimates <- lipidomics %>%
  split_by_metabolite() %>%
  map(generate_model_results) %>%
  list_rbind() %>%
  filter(str_detect(term, "metabolite_"))
model_estimates
```

```{r}
lipidomics %>%
  split_by_metabolite() %>%
  purrr::map(generate_model_results) %>%
  purrr::list_rbind() %>%
  dplyr::filter(stringr::str_detect(term, "metabolite_")) %>%
  add_original_metabolite_names(lipidomics)
```

### figure of model estimates
```{r}
model_estimates <- targets::tar_read(df_model_estimates)
```

```{r}
plot_estimates(model_estimates)
```

```{r}
tar_read(plot_model_estimates)
```


